version: 0.2

env:
  variables:
    FRONTEND_IMAGE: "chatapp-frontend"
    BACKEND_IMAGE: "chatapp-backend"
  git-credential-helper: yes
  secrets-manager:
    REACT_APP_API_URL: "chatapp-alphasense-MAcSmc:REACT_APP_API_URL"

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo installing dependencies
      - n 18
      - cd _infrastructure
      - npm ci
      - cd ..
      - cd frontend
      - npm ci
      - cd ..
      - cd backend
      - npm ci
      - cd ..
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - REPOSITORY_URI=476194719932.dkr.ecr.eu-west-1.amazonaws.com/chatapp-alphasense
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Building the Docker image for the frontend...
      - docker build -t $FRONTEND_IMAGE --build-arg REACT_APP_API_URL=$REACT_APP_API_URL ./frontend
      - echo Building the Docker image for the backend...
      - docker build -t $BACKEND_IMAGE ./backend
  post_build:
    commands:
      - echo Tagging the Docker images...
      - aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 476194719932.dkr.ecr.eu-west-1.amazonaws.com
      - docker tag $FRONTEND_IMAGE "${REPOSITORY_URI}:latest_frontend"
      - docker tag $FRONTEND_IMAGE "${REPOSITORY_URI}:${IMAGE_TAG}_frontend"
      - docker tag $BACKEND_IMAGE "${REPOSITORY_URI}:latest_backend"
      - docker tag $BACKEND_IMAGE "${REPOSITORY_URI}:${IMAGE_TAG}_backend"
      - echo Pushing the Docker images...
      - docker push "${REPOSITORY_URI}:latest_frontend"
      - docker push "${REPOSITORY_URI}:latest_backend"
      - echo Writing image definitions file for frontend...
      - printf '[{"name":"frontend-container","imageUri":"%s"}]' "${REPOSITORY_URI}:latest_frontend" > imagedefinitions-frontend.json
      - echo Writing image definitions file for backend...
      - printf '[{"name":"backend-container","imageUri":"%s"}]' "${REPOSITORY_URI}:latest_backend" > imagedefinitions-backend.json
artifacts:
  secondary-artifacts:
    frontendArtifact:
      files:
        - imagedefinitions-frontend.json
    backendArtifact:
      files:
        - imagedefinitions-backend.json
